#! /bin/sh

sxhkd -m -1 &

xrandr --output DP-2 --off --output eDP-1 --mode 1920x1080 --rotate normal --output DP-1 --off
bspc monitor DP-2 --remove
bspc monitor DP-1 --remove
bspc monitor eDP-1 --reset-desktops $(seq 1 20)

bspc config border_width         3
bspc config window_gap           8

bspc config removal_adjustment   none
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc config normal_border_color '#515151'
bspc config active_border_color '#745369'

bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config pointer_modifier mod4 # super
xsetroot -cursor_name left_ptr

bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
bspc rule -a TelegramDesktop:'Media viewer' state=fullscreen


# Autostart

# Background
~/.fehbg &

# Notifications
dunst &

# Set keyboard, set control tap = escape
{ setxkbmap -option ctrl:swapcaps -option compose:ralt; xcape -e 'Control_L=Escape;Control_R=Escape;#37=Escape' ;} &

# Mount media disk, start mpd, start bar
{ udisksctl mount -b /dev/d/d; ~/scripts/lemonbar/bar_run ;} 2> /tmp/logg &

# Compositor
compton &

# Script to hide bar under fullscreen windows
# bash ~/scripts/lemonbar/bar_fullscreen.sh &

# Sleep sometimes
redshift -l 51:0 &

bspc rule -a KeePassXC:keepassxc -o desktop=10
keepassxc &
