#! /bin/sh

sxhkd -m -1 &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc config normal_border_color '#515151'
bspc config active_border_color '#745369'

bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true
bspc config pointer_modifier mod4 # super
xsetroot -cursor_name left_ptr

bspc rule -a Gimp desktop='^6' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off


# Autostart
# TODO mpdris

# Background
~/.fehbg &

# Notifications
dunst &

# Set keyboard, set control tap = escape
{ setxkbmap -option ctrl:swapcaps -option compose:ralt; xcape -e 'Control_L=Escape;Control_R=Escape' ;} &

# Swipe gestures
libinput-gestures-setup start &

# Mount media disk, start mpd, start bar
{ udisksctl mount -b /dev/d/d; mpd; ~/scripts/lemonbar/bar_run ;} 2> /tmp/logg &

# Compositor
compton --fading --fade-delta 2 &

# Script to hide bar under fullscreen windows
bash ~/scripts/lemonbar/bar_fullscreen.sh &
